common/models/Category.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * This is the model class for table "category".
 *
 * @property integer $id
 * @property integer $level
 * @property string $name
 * @property string $url
 * @property integer $parent
 *
 * @property TagGroup[] $tagGroups
 * @properties Category[] $children
 * @property Product[] $products
 */
class Category extends \yii\db\ActiveRecord
{
    public function init()
    {
        parent::init();
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['parent', 'level'], 'integer'],
            [['name', 'url'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'parent' => 'Parent',
            'url' => 'Url on novus.zakaz.ua'
        ];
    }

    public function beforeSave($insert){
        if ($this->parent > 0){
            $parent = Category::findOne($this->parent);
            if ($parent)
                $this->level = $parent->level+1;
        }
        return parent::beforeSave($insert);
    }

    public function afterDelete()
    {
        $cats = Category::find()->where(['parent' => $this->id])->all();
        foreach ($cats as $cat) {
            echo $cat->delete();
        }
        parent::afterDelete();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTagGroups()
    {
        return $this->hasMany(TagGroup::className(), ['id' => 'tag_group_id'])->viaTable('category_tag_group', ['category_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(Product::className(), ['id' => 'product_id'])->viaTable('product_category', ['category_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChildren()
    {
        return $this->hasMany(Category::className(), ['parent' => 'id'])->orderBy('name');
    }

    public function getParents()
    {
        $result = [];
        $parent = $this;
        while ($parent->parent > 0)
        {
            $parent = Category::findOne($parent->parent);
            if ($parent)
                array_unshift($result, $parent);
        }
        return $result;
    }

    public function getHierarchyAsArray($modifier = null, $parents = null){

        if ($modifier) $val = call_user_func($modifier, $this, $parents);
        else $val = $this;
        $result = [$val];
        if (!$parents) $parents = [$this];
        else $parents []= $this;
        foreach ($this->children as $child)
            $result = ArrayHelper::merge($result, $child->getHierarchyAsArray($modifier, $parents));

        return $result;
    }

    public function fields()
    {
        return ['id', 'name'];
    }

    public function extraFields()
    {
        return ['children', 'tagGroups', 'url', 'parent'];
    }
}

backend/controllers/CategoryController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Category;
use backend\models\CategorySearch;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();

        $categories = $this->getCategoriesList();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'categories' => $categories
            ]);
        }
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $categories = $this->getCategoriesList();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'categories' => $categories
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function getCategoriesList(){
        $categoriesModels = Category::find()->where(['parent' => 0])->with('children')->all();
        $categories = [['id' => 0, 'name' => 'Нет родителя']];

        foreach ($categoriesModels as $cat){
            $categories = ArrayHelper::merge($categories, $cat->getHierarchyAsArray(
                function($category, $parents){
                    $res = '';
                    if (!empty($parents)) {
                        foreach ($parents as $i => $p) {
                            if ($i > 0) $res .= ' → ';
                            $res .= $p->name;
                        }
                        $res .= ' → ';
                    }
                    $res .= $category->name;
                    return ['id' => $category->id, 'name' => $res];
                }
            ));
        }
        return ArrayHelper::map($categories, 'id', 'name');
    }
}

backend/controllers/ProductController.php
<?php

namespace backend\controllers;

use backend\models\ProductForm;
use common\models\Category;
use Yii;
use common\models\Product;
use common\models\ProductSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        //die(Json::encode(explode(",", $searchModel->chains)));
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProductForm();
        $categories = $this->getCategoriesList();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'categories' => $categories
            ]);
        }
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = new ProductForm($this->findModel($id));
        $categories = $this->getCategoriesList();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'categories' => $categories
            ]);
        }
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    protected function getCategoriesList(){
        $categoriesModels = Category::find()->where(['parent' => 0])->with('children')->all();
        $categories = [];

        foreach ($categoriesModels as $cat){
            $categories = ArrayHelper::merge($categories, $cat->getHierarchyAsArray(
                function($category, $parents){
                    $res = '';
                    if (!empty($parents)) {
                        foreach ($parents as $i => $p) {
                            if ($i > 0) $res .= ' → ';
                            $res .= $p->name;
                        }
                        $res .= ' → ';
                    }
                    $res .= $category->name;
                    return ['id' => $category->id, 'name' => $res];
                }
            ));
        }
        return ArrayHelper::map($categories, 'id', 'name');
    }
}

backend/views/category/_form.php
<?php

use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'url')->textInput(['maxlength' => true]) ?>


    <div class="form-group">
        <?= Select2::widget([
            'model' => $model,
            'attribute' => 'parent',
            'data' => $categories,
            'options' => [
                'placeholder' => 'Select category ...',
            ],
        ]); ?>
    </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/category/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = 'Create Category';
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'categories' => $categories
    ]) ?>

</div>

backend/views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\CategorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Categories';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Category', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            ['attribute' => 'id', 'options' => ['style' => 'width:80px']],
            [   'attribute' => 'name',
                'format' => 'html',
                'value' => function($model){
                    if ($model->getChildren()->count() > 0)
                        return Html::a($model->name, \yii\helpers\Url::to(['category/', 'CategorySearch[parent]' => $model->id]));
                    return $model->name;
                }
            ],
            [   'attribute' => 'parent',
                'format' => 'html',
                'value' => function($model){
                    $res = '';
                    $parents = $model->parents;
                    foreach ($parents as $i => $p){
                        if ($i > 0)
                            $res .= ' → ';
                        $res .= Html::a($p->name, \yii\helpers\Url::to(['category/', 'CategorySearch[parent]' => $p->id]));
                    }
                    return $res;
                }
            ],
            ['class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'products' => function ($url, $model){
                        return Html::a('<span class="glyphicon glyphicon-list-alt"></span>',
                            Yii::$app->urlManager->createUrl(['product/index', 'ProductSearch[category]' => $model->id]));
                    }
                ],
                'template' => '{products} {view} {update} {delete}',
            ],
        ],
    ]); ?>

</div>

backend/views/category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = 'Update Category: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="category-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'categories' => $categories
    ]) ?>

</div>

backend/views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Category */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?php
        $parentsHtml = '';
        $parents = $model->parents;
        foreach ($parents as $i => $p){
            if ($i > 0) $parentsHtml .= ' → ';
            $parentsHtml .= Html::a($p->name, \yii\helpers\Url::to(['category/', 'CategorySearch[parent]' => $p->id]));
        }
    ?>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            [
                'format' => 'raw',
                'label' => 'Parents',
                'value' => $parentsHtml
            ],
            'url'
        ],
    ]) ?>

</div>